COMPANIES = [
    {
        "slug": "tcs", "name": "TCS", "industry": "IT Services",
        "description": "A large technology services organization. Use this profile as configurable interview-preparation guidance, not as a statement of guaranteed hiring requirements.",
        "roles": ["Software Engineer", "Software Developer", "Data Analyst"],
        "difficulty": "Beginner to Advanced",
        "skills": ["Programming", "DSA", "OOP", "SQL", "Problem Solving", "Communication"],
        "languages": ["Java", "Python", "C++", "JavaScript"],
        "subjects": ["DSA", "OOP", "DBMS", "OS", "Networks"],
        "stages": ["Screening", "Technical", "HR/Behavioral"],
        "technical_topics": ["Programming fundamentals", "DSA", "OOP", "SQL", "Projects"],
        "behavioral": ["Communication", "Teamwork", "Project discussion"],
    },
    {
        "slug": "infosys", "name": "Infosys", "industry": "IT Services",
        "description": "A global technology and consulting organization. This profile is general preparation guidance rather than an official role requirement.",
        "roles": ["Software Engineer", "Java Developer", "Data Analyst"],
        "difficulty": "Beginner to Advanced",
        "skills": ["Programming", "DSA", "SQL", "OOP", "Problem Solving"],
        "languages": ["Java", "Python", "C++", "JavaScript"],
        "subjects": ["DSA", "DBMS", "OOP", "OS", "Networks"],
        "stages": ["Assessment", "Technical", "HR/Behavioral"],
        "technical_topics": ["Coding", "DSA", "SQL", "Projects"],
        "behavioral": ["Communication", "Situational questions"],
    },
    {
        "slug": "wipro", "name": "Wipro", "industry": "IT Services",
        "description": "A technology services and consulting organization. Interview topics vary by role and hiring process.",
        "roles": ["Software Engineer", "Python Developer", "QA Engineer"],
        "difficulty": "Beginner to Advanced",
        "skills": ["Programming", "OOP", "SQL", "Testing", "Problem Solving"],
        "languages": ["Java", "Python", "C++", "JavaScript"],
        "subjects": ["DSA", "DBMS", "OOP", "OS"],
        "stages": ["Assessment", "Technical", "HR/Behavioral"],
        "technical_topics": ["Programming", "OOP", "SQL", "Projects"],
        "behavioral": ["Communication", "Teamwork"],
    },
    {
        "slug": "accenture", "name": "Accenture", "industry": "Technology & Consulting",
        "description": "A global professional services organization. The simulator uses this as broad role-oriented preparation context.",
        "roles": ["Software Engineer", "Cloud Engineer", "Data Analyst"],
        "difficulty": "Beginner to Advanced",
        "skills": ["Programming", "Cloud", "SQL", "Problem Solving", "Communication"],
        "languages": ["Java", "Python", "JavaScript", "SQL"],
        "subjects": ["DSA", "DBMS", "Cloud", "OOP"],
        "stages": ["Assessment", "Technical", "Communication/HR"],
        "technical_topics": ["Coding", "Cloud", "SQL", "Projects"],
        "behavioral": ["Communication", "Situational questions"],
    },
    {
        "slug": "deloitte", "name": "Deloitte", "industry": "Consulting & Technology",
        "description": "A professional services organization with technology roles across multiple domains.",
        "roles": ["Software Engineer", "Data Analyst", "Cybersecurity Analyst"],
        "difficulty": "Intermediate to Advanced",
        "skills": ["Problem Solving", "SQL", "Programming", "Analytics", "Communication"],
        "languages": ["Python", "Java", "SQL", "JavaScript"],
        "subjects": ["DSA", "DBMS", "Analytics", "Security"],
        "stages": ["Assessment", "Technical", "Behavioral"],
        "technical_topics": ["Problem solving", "SQL", "Projects", "Role-specific skills"],
        "behavioral": ["Communication", "Leadership", "Situational questions"],
    },
    {
        "slug": "cognizant", "name": "Cognizant", "industry": "IT Services",
        "description": "A technology and professional services company. Use the profile for broad practice topics.",
        "roles": ["Programmer Analyst", "Software Engineer", "Data Analyst"],
        "difficulty": "Beginner to Advanced",
        "skills": ["Programming", "SQL", "OOP", "DSA"],
        "languages": ["Java", "Python", "C++", "JavaScript"],
        "subjects": ["DSA", "DBMS", "OOP", "OS"],
        "stages": ["Assessment", "Technical", "HR"],
        "technical_topics": ["Programming", "SQL", "DSA", "Projects"],
        "behavioral": ["Communication", "Teamwork"],
    },
    {
        "slug": "capgemini", "name": "Capgemini", "industry": "IT Services & Consulting",
        "description": "A technology and consulting organization with roles across software and digital engineering.",
        "roles": ["Software Engineer", "Cloud Engineer", "QA Engineer"],
        "difficulty": "Beginner to Advanced",
        "skills": ["Programming", "Testing", "Cloud", "SQL"],
        "languages": ["Java", "Python", "JavaScript", "C++"],
        "subjects": ["DSA", "OOP", "DBMS", "Cloud"],
        "stages": ["Assessment", "Technical", "HR"],
        "technical_topics": ["Coding", "OOP", "SQL", "Testing"],
        "behavioral": ["Communication", "Teamwork"],
    },
    {
        "slug": "ibm", "name": "IBM", "industry": "Technology",
        "description": "A technology company spanning software, cloud, AI and infrastructure.",
        "roles": ["Software Engineer", "AI/ML Engineer", "Cloud Engineer"],
        "difficulty": "Intermediate to Expert",
        "skills": ["Programming", "Cloud", "AI", "Data", "Problem Solving"],
        "languages": ["Python", "Java", "C++", "JavaScript"],
        "subjects": ["DSA", "OOP", "Cloud", "AI/ML"],
        "stages": ["Assessment", "Technical", "Behavioral"],
        "technical_topics": ["Coding", "Cloud", "AI/ML", "Projects"],
        "behavioral": ["Communication", "Collaboration"],
    },
    {
        "slug": "amazon", "name": "Amazon", "industry": "Technology & E-commerce",
        "description": "A technology and commerce company. The simulator uses broad engineering preparation areas and does not claim proprietary hiring criteria.",
        "roles": ["Software Development Engineer", "Data Engineer", "Cloud Engineer"],
        "difficulty": "Intermediate to Expert",
        "skills": ["DSA", "Problem Solving", "System Design", "Coding", "Behavioral"],
        "languages": ["Java", "C++", "Python", "JavaScript"],
        "subjects": ["DSA", "OOP", "DBMS", "OS", "Networks"],
        "stages": ["Assessment", "Technical", "Behavioral"],
        "technical_topics": ["DSA", "Coding", "System Design", "Projects"],
        "behavioral": ["Ownership", "Teamwork", "Situational questions"],
    },
    {
        "slug": "microsoft", "name": "Microsoft", "industry": "Technology",
        "description": "A technology company with engineering roles across software, cloud, data and AI.",
        "roles": ["Software Engineer", "AI/ML Engineer", "Cloud Engineer"],
        "difficulty": "Intermediate to Expert",
        "skills": ["DSA", "Coding", "System Design", "Cloud", "Problem Solving"],
        "languages": ["C++", "C#", "Java", "Python", "JavaScript"],
        "subjects": ["DSA", "OOP", "OS", "Networks", "System Design"],
        "stages": ["Technical", "Behavioral"],
        "technical_topics": ["DSA", "Coding", "System Design", "Projects"],
        "behavioral": ["Collaboration", "Problem solving"],
    },
    {
        "slug": "google", "name": "Google", "industry": "Technology",
        "description": "A technology company with roles in software, data, cloud and AI. The simulator provides general technical preparation.",
        "roles": ["Software Engineer", "Data Scientist", "AI/ML Engineer"],
        "difficulty": "Advanced to Expert",
        "skills": ["DSA", "Algorithms", "Problem Solving", "System Design"],
        "languages": ["C++", "Java", "Python", "Go", "JavaScript"],
        "subjects": ["Algorithms", "DSA", "OS", "Networks", "System Design"],
        "stages": ["Technical", "Behavioral"],
        "technical_topics": ["Algorithms", "Coding", "Design", "Projects"],
        "behavioral": ["Collaboration", "Communication"],
    },
    {
        "slug": "oracle", "name": "Oracle", "industry": "Enterprise Technology",
        "description": "An enterprise technology company with software, database and cloud products.",
        "roles": ["Software Engineer", "Database Developer", "Cloud Engineer"],
        "difficulty": "Intermediate to Advanced",
        "skills": ["Java", "SQL", "DBMS", "Cloud", "DSA"],
        "languages": ["Java", "Python", "C++", "SQL"],
        "subjects": ["DBMS", "SQL", "DSA", "Cloud", "OOP"],
        "stages": ["Assessment", "Technical", "HR"],
        "technical_topics": ["SQL", "DBMS", "Coding", "Cloud"],
        "behavioral": ["Communication", "Teamwork"],
    },
    {
        "slug": "cisco", "name": "Cisco", "industry": "Networking & Technology",
        "description": "A networking and technology company. Preparation includes networking fundamentals and software engineering topics.",
        "roles": ["Software Engineer", "Network Engineer", "Cybersecurity Analyst"],
        "difficulty": "Intermediate to Advanced",
        "skills": ["Networking", "Programming", "Security", "Linux"],
        "languages": ["Python", "C", "C++", "Java"],
        "subjects": ["Networks", "OS", "Security", "DSA"],
        "stages": ["Assessment", "Technical", "Behavioral"],
        "technical_topics": ["Networking", "Coding", "Security", "Projects"],
        "behavioral": ["Communication", "Teamwork"],
    },
    {
        "slug": "adobe", "name": "Adobe", "industry": "Software",
        "description": "A software company focused on creative, document and digital experience products.",
        "roles": ["Software Engineer", "Frontend Developer", "Data Scientist"],
        "difficulty": "Intermediate to Expert",
        "skills": ["DSA", "OOP", "Web", "Problem Solving"],
        "languages": ["C++", "Java", "Python", "JavaScript"],
        "subjects": ["DSA", "OOP", "DBMS", "Web"],
        "stages": ["Coding", "Technical", "Behavioral"],
        "technical_topics": ["DSA", "Coding", "Web", "Projects"],
        "behavioral": ["Collaboration", "Communication"],
    },
    {
        "slug": "salesforce", "name": "Salesforce", "industry": "Cloud Software",
        "description": "A cloud software company. Practice can include software engineering, APIs, databases and platform concepts.",
        "roles": ["Software Engineer", "Backend Developer", "Data Engineer"],
        "difficulty": "Intermediate to Advanced",
        "skills": ["Java", "APIs", "SQL", "OOP", "Cloud"],
        "languages": ["Java", "Python", "JavaScript", "SQL"],
        "subjects": ["OOP", "DBMS", "APIs", "Cloud"],
        "stages": ["Technical", "Behavioral"],
        "technical_topics": ["Coding", "APIs", "SQL", "Projects"],
        "behavioral": ["Communication", "Collaboration"],
    },
    {
        "slug": "jpmorgan", "name": "JPMorgan Chase", "industry": "Financial Services & Technology",
        "description": "A financial services organization with technology roles. Preparation should be adapted to the specific role.",
        "roles": ["Software Engineer", "Data Engineer", "Cybersecurity Analyst"],
        "difficulty": "Intermediate to Advanced",
        "skills": ["Java", "SQL", "DSA", "Systems", "Security"],
        "languages": ["Java", "Python", "C++", "SQL"],
        "subjects": ["DSA", "DBMS", "OS", "Security"],
        "stages": ["Assessment", "Technical", "Behavioral"],
        "technical_topics": ["Coding", "SQL", "Systems", "Projects"],
        "behavioral": ["Communication", "Teamwork"],
    },
    {
        "slug": "goldman-sachs", "name": "Goldman Sachs", "industry": "Financial Services & Technology",
        "description": "A financial services organization with engineering and data roles.",
        "roles": ["Software Engineer", "Data Analyst", "Data Engineer"],
        "difficulty": "Intermediate to Advanced",
        "skills": ["DSA", "Python", "Java", "SQL", "Problem Solving"],
        "languages": ["Java", "Python", "C++", "SQL"],
        "subjects": ["DSA", "DBMS", "OOP", "Algorithms"],
        "stages": ["Assessment", "Technical", "Behavioral"],
        "technical_topics": ["Coding", "Algorithms", "SQL", "Projects"],
        "behavioral": ["Communication", "Teamwork"],
    },
    {
        "slug": "qualcomm", "name": "Qualcomm", "industry": "Semiconductors & Wireless Technology",
        "description": "A semiconductor and wireless technology company with embedded and software engineering roles.",
        "roles": ["Software Engineer", "Embedded Engineer", "AI/ML Engineer"],
        "difficulty": "Intermediate to Expert",
        "skills": ["C/C++", "Embedded", "Algorithms", "Computer Architecture"],
        "languages": ["C", "C++", "Python"],
        "subjects": ["DSA", "OS", "Computer Architecture", "Embedded"],
        "stages": ["Coding", "Technical", "Behavioral"],
        "technical_topics": ["C/C++", "Embedded", "OS", "Architecture"],
        "behavioral": ["Problem solving", "Communication"],
    },
    {
        "slug": "intel", "name": "Intel", "industry": "Semiconductors & Technology",
        "description": "A semiconductor technology company with hardware, software and AI-related engineering roles.",
        "roles": ["Software Engineer", "Embedded Engineer", "AI/ML Engineer"],
        "difficulty": "Intermediate to Expert",
        "skills": ["C/C++", "Algorithms", "Architecture", "AI"],
        "languages": ["C", "C++", "Python"],
        "subjects": ["DSA", "OS", "Architecture", "AI/ML"],
        "stages": ["Coding", "Technical", "Behavioral"],
        "technical_topics": ["C/C++", "Algorithms", "Systems", "Projects"],
        "behavioral": ["Collaboration", "Communication"],
    },
    {
        "slug": "nvidia", "name": "NVIDIA", "industry": "AI & Computing",
        "description": "A computing technology company with roles spanning software, accelerated computing and AI.",
        "roles": ["Software Engineer", "AI/ML Engineer", "Systems Engineer"],
        "difficulty": "Advanced to Expert",
        "skills": ["C++", "Python", "Algorithms", "AI", "Systems"],
        "languages": ["C++", "Python", "CUDA"],
        "subjects": ["DSA", "Architecture", "AI/ML", "Systems"],
        "stages": ["Coding", "Technical", "Behavioral"],
        "technical_topics": ["Algorithms", "C++", "AI", "Systems"],
        "behavioral": ["Problem solving", "Communication"],
    },
    {
        "slug": "walmart", "name": "Walmart", "industry": "Retail Technology",
        "description": "A retail organization with large-scale technology and data roles.",
        "roles": ["Software Engineer", "Data Engineer", "Cloud Engineer"],
        "difficulty": "Intermediate to Advanced",
        "skills": ["Java", "Python", "SQL", "Cloud", "DSA"],
        "languages": ["Java", "Python", "JavaScript", "SQL"],
        "subjects": ["DSA", "DBMS", "Cloud", "OOP"],
        "stages": ["Assessment", "Technical", "Behavioral"],
        "technical_topics": ["Coding", "SQL", "Cloud", "Projects"],
        "behavioral": ["Collaboration", "Problem solving"],
    },
    {
        "slug": "paypal", "name": "PayPal", "industry": "Fintech",
        "description": "A digital payments technology company with software, data and security roles.",
        "roles": ["Software Engineer", "Backend Developer", "Data Scientist"],
        "difficulty": "Intermediate to Advanced",
        "skills": ["Java", "APIs", "SQL", "Security", "DSA"],
        "languages": ["Java", "Python", "C++", "JavaScript"],
        "subjects": ["DSA", "DBMS", "APIs", "Security"],
        "stages": ["Coding", "Technical", "Behavioral"],
        "technical_topics": ["Coding", "APIs", "Security", "Projects"],
        "behavioral": ["Communication", "Teamwork"],
    },
    {
        "slug": "zoho", "name": "Zoho", "industry": "Software",
        "description": "A software product company. The simulator uses general software engineering preparation areas.",
        "roles": ["Software Developer", "Java Developer", "QA Engineer"],
        "difficulty": "Beginner to Advanced",
        "skills": ["Programming", "DSA", "OOP", "Problem Solving"],
        "languages": ["Java", "C++", "Python", "JavaScript"],
        "subjects": ["DSA", "OOP", "DBMS", "OS"],
        "stages": ["Coding", "Technical", "HR"],
        "technical_topics": ["Programming", "DSA", "OOP", "Projects"],
        "behavioral": ["Communication", "Teamwork"],
    },
    {
        "slug": "freshworks", "name": "Freshworks", "industry": "SaaS",
        "description": "A SaaS software company. Preparation should be adapted to the selected engineering role.",
        "roles": ["Software Engineer", "Frontend Developer", "Backend Developer"],
        "difficulty": "Intermediate to Advanced",
        "skills": ["Programming", "Web", "APIs", "SQL", "DSA"],
        "languages": ["Java", "Python", "JavaScript", "SQL"],
        "subjects": ["DSA", "Web", "DBMS", "APIs"],
        "stages": ["Coding", "Technical", "Behavioral"],
        "technical_topics": ["Coding", "Web", "APIs", "Projects"],
        "behavioral": ["Communication", "Collaboration"],
    },
]

BRANCHES = [
    {"name": "Computer Science Engineering", "icon": "💻"},
    {"name": "Information Technology", "icon": "🖥️"},
    {"name": "Electronics and Communication Engineering", "icon": "📡"},
    {"name": "Electrical and Electronics Engineering", "icon": "⚡"},
    {"name": "Mechanical Engineering", "icon": "⚙️"},
    {"name": "Civil Engineering", "icon": "🏗️"},
    {"name": "Artificial Intelligence & Machine Learning", "icon": "🤖"},
    {"name": "Data Science", "icon": "📊"},
]

ROLES = [
    {"name": "Software Developer"}, {"name": "Software Engineer"},
    {"name": "Java Developer"}, {"name": "Python Developer"},
    {"name": "Frontend Developer"}, {"name": "Backend Developer"},
    {"name": "Full Stack Developer"}, {"name": "Data Analyst"},
    {"name": "Data Scientist"}, {"name": "AI/ML Engineer"},
    {"name": "Cloud Engineer"}, {"name": "DevOps Engineer"},
    {"name": "Cybersecurity Analyst"}, {"name": "Database Developer"},
    {"name": "QA Engineer"}, {"name": "Mobile App Developer"},
]

DIFFICULTIES = [
    {"name": "Beginner", "level": 1, "focus": "basic programming, simple concepts, simple coding and fundamentals"},
    {"name": "Intermediate", "level": 2, "focus": "DSA, OOP, DBMS, OS, networks and practical coding"},
    {"name": "Advanced", "level": 3, "focus": "advanced DSA, system design basics, optimization and real-world scenarios"},
    {"name": "Expert", "level": 4, "focus": "difficult coding, architecture, optimization and advanced role-specific problems"},
]

MODES = [
    {"name": "Typing", "icon": "⌨️"},
    {"name": "Voice", "icon": "🎙️"},
    {"name": "Video", "icon": "🎥"},
]

RESOURCES = [
    {"subject": "C", "title": "C Programming Language", "description": "Language fundamentals and standard library reference.", "url": "https://en.cppreference.com/w/c", "type": "Documentation"},
    {"subject": "C++", "title": "cppreference C++", "description": "Comprehensive C++ language and library reference.", "url": "https://en.cppreference.com/w/", "type": "Documentation"},
    {"subject": "Java", "title": "Oracle Java Documentation", "description": "Official Java documentation and tutorials.", "url": "https://docs.oracle.com/en/java/", "type": "Documentation"},
    {"subject": "Python", "title": "Python Documentation", "description": "Official Python language documentation.", "url": "https://docs.python.org/3/", "type": "Documentation"},
    {"subject": "JavaScript", "title": "MDN JavaScript Guide", "description": "Web-standard JavaScript learning and reference material.", "url": "https://developer.mozilla.org/en-US/docs/Web/JavaScript", "type": "Documentation"},
    {"subject": "DSA", "title": "GeeksforGeeks DSA", "description": "Practice and explanations for common data structures and algorithms.", "url": "https://www.geeksforgeeks.org/data-structures/", "type": "Practice"},
    {"subject": "SQL", "title": "SQLBolt", "description": "Interactive SQL lessons and exercises.", "url": "https://sqlbolt.com/", "type": "Practice"},
    {"subject": "Flask", "title": "Flask Documentation", "description": "Official Flask documentation.", "url": "https://flask.palletsprojects.com/", "type": "Documentation"},
    {"subject": "React", "title": "React Documentation", "description": "Official React documentation.", "url": "https://react.dev/", "type": "Documentation"},
    {"subject": "Machine Learning", "title": "scikit-learn User Guide", "description": "Official machine learning library guide.", "url": "https://scikit-learn.org/stable/user_guide.html", "type": "Documentation"},
    {"subject": "Generative AI", "title": "Hugging Face Learn", "description": "Courses and learning resources for modern AI.", "url": "https://huggingface.co/learn", "type": "Learning"},
    {"subject": "LLMs", "title": "OpenAI Cookbook", "description": "Practical patterns for LLM application development.", "url": "https://cookbook.openai.com/", "type": "Learning"},
    {"subject": "Interview", "title": "STAR Method", "description": "A structured method for behavioral interview answers.", "url": "https://www.indeed.com/career-advice/interviewing/how-to-use-the-star-interview-method", "type": "Interview"},
]

BOOKS = [
    {"subject": "Data Structures", "title": "Introduction to Algorithms", "author": "Thomas H. Cormen et al.", "description": "A comprehensive algorithms reference.", "url": "https://mitpress.mit.edu/9780262046305/introduction-to-algorithms/"},
    {"subject": "Operating Systems", "title": "Operating System Concepts", "author": "Abraham Silberschatz, Peter B. Galvin, Greg Gagne", "description": "A standard operating systems textbook.", "url": "https://www.os-book.com/OS10/"},
    {"subject": "DBMS", "title": "Database System Concepts", "author": "Abraham Silberschatz, Henry F. Korth, S. Sudarshan", "description": "Database concepts, SQL and database design.", "url": "https://www.db-book.com/"},
    {"subject": "Computer Networks", "title": "Computer Networking: A Top-Down Approach", "author": "James F. Kurose, Keith W. Ross", "description": "Networking concepts taught from applications downward.", "url": "https://gaia.cs.umass.edu/kurose_ross/"},
    {"subject": "Java", "title": "Effective Java", "author": "Joshua Bloch", "description": "Practical guidance for writing robust Java.", "url": "https://www.oreilly.com/library/view/effective-java/9780134686097/"},
    {"subject": "Python", "title": "Fluent Python", "author": "Luciano Ramalho", "description": "Deep practical Python programming.", "url": "https://www.oreilly.com/library/view/fluent-python-2nd/9781492056348/"},
    {"subject": "Coding Interviews", "title": "Cracking the Coding Interview", "author": "Gayle Laakmann McDowell", "description": "Interview-oriented programming practice.", "url": "https://www.crackingthecodinginterview.com/"},
]

CODING_PLATFORMS = [
    {"name": "LeetCode", "url": "https://leetcode.com/", "description": "Algorithm and coding interview practice."},
    {"name": "HackerRank", "url": "https://www.hackerrank.com/", "description": "Programming, SQL and skill assessments."},
    {"name": "CodeChef", "url": "https://www.codechef.com/", "description": "Competitive programming and practice."},
    {"name": "GeeksforGeeks", "url": "https://www.geeksforgeeks.org/", "description": "DSA explanations and interview practice."},
    {"name": "HackerEarth", "url": "https://www.hackerearth.com/", "description": "Programming challenges and assessments."},
    {"name": "Codeforces", "url": "https://codeforces.com/", "description": "Competitive programming contests and practice."},
]
